import bubbleSource from './python/bubble_sort.py?raw';
import cocktailSource from './python/cocktail_sort.py?raw';
import cycleSource from './python/cycle_sort.py?raw';
import gnomeSource from './python/gnome_sort.py?raw';
import heapSource from './python/heap_sort.py?raw';
import insertionSource from './python/insertion_sort.py?raw';
import mergeSource from './python/merge_sort.py?raw';
import quickSource from './python/quick_sort.py?raw';
import selectionSource from './python/selection_sort.py?raw';
import shellSource from './python/shell_sort.py?raw';
import binaryInsertionSource from './python/binary_insertion_sort.py?raw';
import combSource from './python/comb_sort.py?raw';
import naturalMergeSource from './python/natural_merge_sort.py?raw';
import oddEvenSource from './python/odd_even_sort.py?raw';
import pancakeSource from './python/pancake_sort.py?raw';
import threeWayQuickSource from './python/three_way_quick_sort.py?raw';
import hoareQuickSource from './python/hoare_quick_sort.py?raw';
import dualPivotQuickSource from './python/dual_pivot_quick_sort.py?raw';
import medianThreeQuickSource from './python/median_three_quick_sort.py?raw';
import bottomUpMergeSource from './python/bottom_up_merge_sort.py?raw';
import inPlaceMergeSource from './python/in_place_merge_sort.py?raw';
import introSource from './python/intro_sort.py?raw';
import timSource from './python/tim_sort.py?raw';
import tournamentSource from './python/tournament_sort.py?raw';
import patienceSource from './python/patience_sort.py?raw';
import treeSource from './python/tree_sort.py?raw';
import strandSource from './python/strand_sort.py?raw';
import countingSource from './python/counting_sort.py?raw';
import radixLsdSource from './python/radix_lsd_sort.py?raw';
import bucketSource from './python/bucket_sort.py?raw';
import type { AlgorithmContract, AlgorithmDefinition, AlgorithmId } from './types';

const ordered = [1, 2, 3, 4, 5, 6, 7, 8];
const reversed = [8, 7, 6, 5, 4, 3, 2, 1];
const mixed = [8, 3, 6, 2, 7, 1, 5, 4];

type SortingAlgorithmMetadata = Omit<AlgorithmDefinition, 'kind' | 'problem' | 'contract'> & {
  contract?: AlgorithmContract;
};

const SORTING_ALGORITHMS: SortingAlgorithmMetadata[] = [
  {
    id: 'bubble',
    name: 'Bubble Sort',
    family: 'Exchange',
    level: 'Beginner',
    summary: 'Repeatedly moves the largest remaining value to the end through adjacent swaps.',
    explanation: [
      'Compare adjacent values.',
      'Swap each strict inversion.',
      'Shrink the unsorted boundary after every pass.',
    ],
    limitation: 'Quadratic work makes it unsuitable for large inputs.',
    complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(1)' },
    traits: { stable: true, inPlace: true, recursive: false },
    source: bubbleSource,
    examples: { default: mixed, bestCase: ordered, worstCase: reversed },
    tags: ['adjacent', 'swap', 'adaptive', 'fundamentals'],
  },
  {
    id: 'selection',
    name: 'Selection Sort',
    family: 'Selection',
    level: 'Beginner',
    summary: 'Finds the minimum of each unsorted suffix and places it at the front.',
    explanation: [
      'Scan the unsorted suffix.',
      'Remember its minimum index.',
      'Swap the minimum into the current position.',
    ],
    limitation: 'Always performs quadratic comparisons, even on sorted data.',
    complexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(1)' },
    traits: { stable: false, inPlace: true, recursive: false },
    source: selectionSource,
    examples: { default: mixed, bestCase: ordered, worstCase: reversed },
    tags: ['minimum', 'few writes', 'scan'],
  },
  {
    id: 'insertion',
    name: 'Insertion Sort',
    family: 'Insertion',
    level: 'Beginner',
    summary: 'Builds a sorted prefix by inserting each new value into its correct position.',
    explanation: ['Save the next value.', 'Shift larger prefix values right.', 'Insert the saved value into the gap.'],
    limitation: 'Reverse-ordered inputs require quadratic shifts.',
    complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(1)' },
    traits: { stable: true, inPlace: true, recursive: false },
    source: insertionSource,
    examples: { default: [1, 2, 4, 3, 5, 7, 6, 8], bestCase: ordered, worstCase: reversed },
    tags: ['adaptive', 'nearly sorted', 'shift', 'online'],
  },
  {
    id: 'cocktail',
    name: 'Cocktail Sort',
    family: 'Exchange',
    level: 'Intermediate',
    summary: 'Alternates bubble passes in both directions to move both extremes at once.',
    explanation: [
      'Bubble the largest value right.',
      'Bubble the smallest value left.',
      'Narrow both boundaries until no swaps remain.',
    ],
    limitation: 'Bidirectional passes improve some inputs but remain quadratic.',
    complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(1)' },
    traits: { stable: true, inPlace: true, recursive: false },
    source: cocktailSource,
    examples: { default: mixed, bestCase: ordered, worstCase: reversed },
    tags: ['bidirectional', 'adjacent', 'swap', 'adaptive'],
  },
  {
    id: 'gnome',
    name: 'Gnome Sort',
    family: 'Insertion',
    level: 'Beginner',
    summary: 'Walks forward through ordered neighbors and steps backward after each swap.',
    explanation: [
      'Compare with the predecessor.',
      'Advance when values are ordered.',
      'Otherwise swap and step backward.',
    ],
    limitation: 'Simple control flow comes with quadratic worst-case movement.',
    complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(1)' },
    traits: { stable: true, inPlace: true, recursive: false },
    source: gnomeSource,
    examples: { default: mixed, bestCase: ordered, worstCase: reversed },
    tags: ['local', 'adjacent', 'adaptive', 'simple'],
  },
  {
    id: 'shell',
    name: 'Shell Sort',
    family: 'Insertion',
    level: 'Intermediate',
    summary: 'Insertion-sorts distant values across shrinking gaps before a final local pass.',
    explanation: [
      'Start with a gap of n / 2.',
      'Insertion-sort each gap-connected sequence.',
      'Halve the gap until it reaches one.',
    ],
    limitation: 'Performance depends strongly on the selected gap sequence.',
    complexity: {
      best: 'O(n log n)',
      average: '≈ O(n^1.5)',
      worst: 'O(n²)',
      memory: 'O(1)',
      note: 'Halving-gap implementation; bounds are gap-dependent.',
    },
    traits: { stable: false, inPlace: true, recursive: false },
    source: shellSource,
    examples: { default: mixed, bestCase: ordered, worstCase: reversed },
    tags: ['gaps', 'insertion', 'gap-dependent'],
  },
  {
    id: 'merge',
    name: 'Merge Sort',
    family: 'Divide & Conquer',
    level: 'Intermediate',
    summary: 'Recursively sorts two halves and stably merges them through a buffer.',
    explanation: [
      'Divide the range in half.',
      'Recursively sort both halves.',
      'Merge the ordered halves into one range.',
    ],
    limitation: 'Predictable speed requires an auxiliary O(n) buffer.',
    complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)', memory: 'O(n)' },
    traits: { stable: true, inPlace: false, recursive: true },
    source: mergeSource,
    examples: { default: mixed, bestCase: ordered, worstCase: [1, 5, 3, 7, 2, 6, 4, 8] },
    tags: ['recursive', 'stable', 'buffer', 'predictable'],
  },
  {
    id: 'quick',
    name: 'Quick Sort',
    family: 'Divide & Conquer',
    level: 'Intermediate',
    summary: 'Partitions values around a pivot and recursively sorts both resulting ranges.',
    explanation: [
      'Choose the last value as pivot.',
      'Move smaller values before it.',
      'Place the pivot and recurse on both sides.',
    ],
    limitation: 'A last-element pivot degrades to O(n²) on sorted and equal data.',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n²)',
      memory: 'O(log n)*',
      note: 'O(n) stack in the worst case.',
    },
    traits: { stable: false, inPlace: true, recursive: true },
    source: quickSource,
    examples: { default: mixed, bestCase: [1, 3, 2, 5, 7, 6, 4], worstCase: ordered },
    tags: ['pivot', 'partition', 'recursive', 'fast average'],
  },
  {
    id: 'heap',
    name: 'Heap Sort',
    family: 'Heap',
    level: 'Advanced',
    summary: 'Builds a max heap and repeatedly extracts its root into the final position.',
    explanation: [
      'Sift values into a max heap.',
      'Swap the root with the active end.',
      'Restore the reduced heap and repeat.',
    ],
    limitation: 'Excellent bounds, but poor locality and no stability.',
    complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)', memory: 'O(1)' },
    traits: { stable: false, inPlace: true, recursive: false },
    source: heapSource,
    examples: { default: mixed, bestCase: reversed, worstCase: ordered },
    tags: ['heap', 'guaranteed', 'in-place', 'selection'],
  },
  {
    id: 'cycle',
    name: 'Cycle Sort',
    family: 'Selection',
    level: 'Advanced',
    summary: 'Places items by final rank and rotates each permutation cycle with minimal writes.',
    explanation: [
      'Count values smaller than the current item.',
      'Skip occupied duplicate ranks.',
      'Rotate displaced values until the cycle closes.',
    ],
    limitation: 'Minimizes writes but still performs quadratic comparisons.',
    complexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(1)' },
    traits: { stable: false, inPlace: true, recursive: false },
    source: cycleSource,
    examples: { default: [3, 1, 2, 1, 3, 2], bestCase: ordered, worstCase: [2, 3, 4, 5, 6, 7, 8, 1] },
    tags: ['minimal writes', 'cycles', 'rank', 'flash memory'],
  },
  {
    id: 'comb',
    name: 'Comb Sort',
    family: 'Exchange',
    level: 'Intermediate',
    summary: 'Eliminates distant inversions with shrinking gaps before finishing as Bubble Sort.',
    explanation: [
      'Start with a gap spanning the array.',
      'Compare and swap values separated by that gap.',
      'Shrink the gap by 1.3 until a swap-free local pass.',
    ],
    limitation: 'Faster than Bubble Sort in practice, but still has quadratic worst-case work.',
    complexity: {
      best: 'O(n log n)',
      average: '≈ O(n²)',
      worst: 'O(n²)',
      memory: 'O(1)',
      note: 'Practical behavior depends on the shrink factor.',
    },
    traits: { stable: false, inPlace: true, recursive: false },
    source: combSource,
    examples: { default: mixed, bestCase: ordered, worstCase: [8, 4, 6, 2, 7, 3, 5, 1] },
    tags: ['gaps', 'exchange', 'shrink factor', 'bubble variant'],
  },
  {
    id: 'odd-even',
    name: 'Odd-Even Sort',
    family: 'Exchange',
    level: 'Beginner',
    summary: 'Alternates independent odd and even adjacent comparisons until no inversion remains.',
    explanation: [
      'Compare odd-indexed neighbor pairs.',
      'Compare even-indexed neighbor pairs.',
      'Repeat both phases until neither performs a swap.',
    ],
    limitation: 'Its parallel structure is useful conceptually, but sequential execution remains quadratic.',
    complexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(1)' },
    traits: { stable: true, inPlace: true, recursive: false },
    source: oddEvenSource,
    examples: { default: mixed, bestCase: ordered, worstCase: reversed },
    tags: ['parallel', 'adjacent', 'phases', 'stable'],
  },
  {
    id: 'pancake',
    name: 'Pancake Sort',
    family: 'Selection',
    level: 'Intermediate',
    summary: 'Moves each maximum into place using only prefix reversals.',
    explanation: [
      'Find the maximum in the active prefix.',
      'Flip it to the front when necessary.',
      'Flip the whole prefix to move it to its final position.',
    ],
    limitation: 'The unusual flip operation is educational but performs quadratic comparisons and writes.',
    complexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(1)' },
    traits: { stable: false, inPlace: true, recursive: false },
    source: pancakeSource,
    examples: { default: [3, 6, 1, 8, 4, 2, 7, 5], bestCase: ordered, worstCase: reversed },
    tags: ['prefix reversal', 'selection', 'flip', 'unusual operations'],
  },
  {
    id: 'binary-insertion',
    name: 'Binary Insertion Sort',
    family: 'Insertion',
    level: 'Intermediate',
    summary: 'Uses binary search to locate each insertion point before shifting the sorted prefix.',
    explanation: [
      'Take the next value from the unsorted suffix.',
      'Binary-search its stable insertion position.',
      'Shift the suffix of the prefix and fill the gap.',
    ],
    limitation: 'Binary search reduces comparisons, but element shifts still require quadratic time.',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n²)',
      worst: 'O(n²)',
      memory: 'O(1)',
      note: 'Best-case comparisons are O(n log n), unlike linear adaptive insertion sort.',
    },
    traits: { stable: true, inPlace: true, recursive: false },
    source: binaryInsertionSource,
    examples: { default: [1, 3, 5, 7, 2, 4, 6, 8], bestCase: ordered, worstCase: reversed },
    tags: ['binary search', 'stable', 'shift', 'few comparisons'],
  },
  {
    id: 'three-way-quick',
    name: 'Three-Way Quick Sort',
    family: 'Divide & Conquer',
    level: 'Advanced',
    summary: 'Partitions values into less-than, equal-to, and greater-than pivot regions.',
    explanation: [
      'Choose the first value as pivot.',
      'Grow three regions with a Dutch-national-flag partition.',
      'Recurse only on the less and greater regions.',
    ],
    limitation: 'Excellent for duplicates, but a poor pivot still causes quadratic recursion on ordered unique data.',
    complexity: {
      best: 'O(n)',
      average: 'O(n log n)',
      worst: 'O(n²)',
      memory: 'O(log n)*',
      note: 'Linear when all keys are equal; recursion can reach O(n).',
    },
    traits: { stable: false, inPlace: true, recursive: true },
    source: threeWayQuickSource,
    examples: { default: [3, 1, 3, 2, 1, 3, 2, 1], bestCase: [4, 4, 4, 4, 4, 4, 4, 4], worstCase: ordered },
    tags: ['duplicates', 'three-way partition', 'recursive', 'Dutch flag'],
  },
  {
    id: 'natural-merge',
    name: 'Natural Merge Sort',
    family: 'Divide & Conquer',
    level: 'Advanced',
    summary: 'Detects existing sorted runs and repeatedly merges adjacent runs until one remains.',
    explanation: [
      'Scan the input for naturally ordered runs.',
      'Stably merge adjacent run pairs into a buffer.',
      'Repeat until the run list collapses to one range.',
    ],
    limitation: 'Adaptive to existing order, but requires an auxiliary buffer for merging.',
    complexity: { best: 'O(n)', average: 'O(n log n)', worst: 'O(n log n)', memory: 'O(n)' },
    traits: { stable: true, inPlace: false, recursive: false },
    source: naturalMergeSource,
    examples: { default: [1, 4, 7, 2, 5, 8, 3, 6], bestCase: ordered, worstCase: reversed },
    tags: ['natural runs', 'adaptive', 'stable', 'merge'],
  },
  {
    id: 'hoare-quick',
    name: 'Hoare Quick Sort',
    family: 'Divide & Conquer',
    level: 'Advanced',
    summary: 'Partitions around a middle value with inward-moving scans, then recursively sorts both sides.',
    explanation: [
      'Choose the middle value as pivot.',
      'Scan inward and swap values that belong across the partition.',
      'Recurse on the ranges outside the crossed pointers.',
    ],
    limitation:
      'Middle-position pivoting is deterministic and can still produce quadratic recursion on adversarial inputs.',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n²)',
      memory: 'O(log n)*',
      note: 'The recursion stack can grow to O(n) after repeatedly unbalanced partitions.',
    },
    traits: { stable: false, inPlace: true, recursive: true },
    source: hoareQuickSource,
    examples: {
      default: [7, 2, 6, 3, 8, 1, 5, 4],
      bestCase: [1, 3, 2, 4, 6, 5, 7],
      worstCase: [1, 2, 3, 4, 8, 6, 7, 5],
    },
    tags: ['Hoare partition', 'two pointers', 'middle pivot', 'in-place'],
  },
  {
    id: 'dual-pivot-quick',
    name: 'Dual-Pivot Quick Sort',
    family: 'Divide & Conquer',
    level: 'Advanced',
    summary: 'Uses two endpoint pivots to divide the array into three ranges in one partition pass.',
    explanation: [
      'Order the endpoint pivots.',
      'Partition values below, between, and above the two pivots.',
      'Place both pivots and recurse on the three resulting ranges.',
    ],
    limitation: 'Endpoint pivots create highly unbalanced partitions on already ordered inputs.',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n²)',
      memory: 'O(log n)*',
      note: 'Unbalanced recursion can require an O(n) stack.',
    },
    traits: { stable: false, inPlace: true, recursive: true },
    source: dualPivotQuickSource,
    examples: { default: [6, 3, 8, 2, 7, 1, 5, 4], bestCase: [3, 1, 4, 2, 7, 5, 8, 6], worstCase: ordered },
    tags: ['two pivots', 'three-way partition', 'recursive', 'in-place'],
  },
  {
    id: 'median-three-quick',
    name: 'Median-of-Three Quick Sort',
    family: 'Divide & Conquer',
    level: 'Advanced',
    summary: 'Chooses the median of the first, middle, and last values before partitioning with two scans.',
    explanation: [
      'Order the first, middle, and last candidates.',
      'Use their median as the partition pivot.',
      'Scan inward, swap misplaced values, and recurse on both sides.',
    ],
    limitation:
      'Sampling three positions reduces common bad pivots but does not eliminate quadratic adversarial cases.',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n²)',
      memory: 'O(log n)*',
      note: 'Worst-case partitions can grow the recursion stack to O(n).',
    },
    traits: { stable: false, inPlace: true, recursive: true },
    source: medianThreeQuickSource,
    examples: { default: mixed, bestCase: [1, 3, 2, 4, 6, 5, 8, 7], worstCase: [1, 2, 3, 4, 8, 6, 7, 5] },
    tags: ['median of three', 'pivot sampling', 'two pointers', 'in-place'],
  },
  {
    id: 'bottom-up-merge',
    name: 'Bottom-Up Merge Sort',
    family: 'Divide & Conquer',
    level: 'Intermediate',
    summary: 'Iteratively merges adjacent runs of doubling width until the whole array is ordered.',
    explanation: [
      'Treat each single value as a sorted run.',
      'Stably merge neighboring runs through an auxiliary array.',
      'Double the run width and repeat until one run remains.',
    ],
    limitation: 'It avoids recursion but still allocates an auxiliary array as large as the input.',
    complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)', memory: 'O(n)' },
    traits: { stable: true, inPlace: false, recursive: false },
    source: bottomUpMergeSource,
    examples: { default: [7, 3, 5, 1, 8, 4, 6, 2], bestCase: ordered, worstCase: reversed },
    tags: ['iterative', 'stable', 'width doubling', 'buffer'],
  },
  {
    id: 'in-place-merge',
    name: 'In-Place Merge Sort',
    family: 'Divide & Conquer',
    level: 'Advanced',
    summary: 'Recursively sorts halves and merges them by shifting out-of-order right-side values into place.',
    explanation: [
      'Recursively sort the left and right halves.',
      'Compare the fronts of both sorted ranges.',
      'Shift the left range right to insert each smaller right-side value.',
    ],
    limitation: 'Removing the merge buffer saves space but repeated shifts raise worst-case time to O(n²).',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n²)',
      worst: 'O(n²)',
      memory: 'O(log n)',
      note: 'Auxiliary storage is the recursive call stack; merging itself uses constant space.',
    },
    traits: { stable: true, inPlace: true, recursive: true },
    source: inPlaceMergeSource,
    examples: { default: [1, 4, 7, 8, 2, 3, 5, 6], bestCase: ordered, worstCase: reversed },
    tags: ['rotation by shifting', 'stable', 'low memory', 'recursive'],
  },
  {
    id: 'intro',
    name: 'Introsort',
    family: 'Hybrid',
    level: 'Advanced',
    summary: 'Combines median-of-three Quick Sort, Heap Sort fallback, and Insertion Sort for small ranges.',
    explanation: [
      'Quick-sort large ranges while tracking a depth budget.',
      'Switch to Heap Sort if partitions consume the budget.',
      'Finish ranges of at most sixteen values with Insertion Sort.',
    ],
    limitation: 'Its guaranteed bound requires substantially more machinery than any component algorithm alone.',
    complexity: {
      best: 'O(n log n)',
      average: 'O(n log n)',
      worst: 'O(n log n)',
      memory: 'O(log n)',
      note: 'An explicit pending-range stack replaces recursive calls.',
    },
    traits: { stable: false, inPlace: true, recursive: false },
    source: introSource,
    examples: {
      default: [12, 3, 9, 1, 14, 6, 11, 2, 16, 5, 8, 4, 15, 7, 13, 10, 18, 17],
      bestCase: ordered,
      worstCase: reversed,
    },
    tags: ['hybrid', 'depth limit', 'heap fallback', 'small-range insertion'],
  },
  {
    id: 'tim',
    name: 'Tim Sort',
    family: 'Hybrid',
    level: 'Advanced',
    summary: 'Discovers natural runs, extends short ones with Insertion Sort, and merges them under balance rules.',
    explanation: [
      'Detect ascending or strictly descending runs and reverse descending ones.',
      'Extend short runs to minrun length with stable Insertion Sort.',
      'Maintain balanced run sizes while stably merging until one run remains.',
    ],
    limitation:
      'Run management and merge buffering make the implementation complex and require linear auxiliary memory.',
    complexity: { best: 'O(n)', average: 'O(n log n)', worst: 'O(n log n)', memory: 'O(n)' },
    traits: { stable: true, inPlace: false, recursive: false },
    source: timSource,
    examples: {
      default: [1, 3, 5, 7, 9, 2, 4, 6, 8, 10],
      bestCase: ordered,
      worstCase: [10, 8, 6, 4, 2, 9, 7, 5, 3, 1],
    },
    tags: ['natural runs', 'adaptive', 'stable', 'merge invariants'],
  },
  {
    id: 'tournament',
    name: 'Tournament Sort',
    family: 'Selection',
    level: 'Advanced',
    summary: 'Builds a knockout tree of contenders and repeatedly emits the current minimum winner.',
    explanation: [
      'Place input positions at the leaves of a complete tournament tree.',
      'Propagate the smaller contender from each match to the root.',
      'Remove each champion and replay only matches on its path.',
    ],
    limitation: 'Predictable logarithmic selection comes at the cost of multiple linear auxiliary structures.',
    complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)', memory: 'O(n)' },
    traits: { stable: true, inPlace: false, recursive: false },
    source: tournamentSource,
    examples: { default: [8, 3, 7, 1, 6, 2, 5, 4], bestCase: ordered, worstCase: reversed },
    tags: ['tournament tree', 'repeated minimum', 'stable', 'selection'],
  },
  {
    id: 'patience',
    name: 'Patience Sort',
    family: 'Hybrid',
    level: 'Advanced',
    summary: 'Deals values into ordered piles, then heap-merges the exposed pile tops.',
    explanation: [
      'Binary-search the leftmost pile whose top is at least the next value.',
      'Place the value on that pile or begin a new one.',
      'Use a min-heap to repeatedly collect the smallest exposed pile top.',
    ],
    limitation:
      'It requires linear auxiliary storage and reverses the relative order of equal values placed on one pile.',
    complexity: {
      best: 'O(n)',
      average: 'O(n log n)',
      worst: 'O(n log n)',
      memory: 'O(n)',
      note: 'Reverse-ordered input forms one pile and can be processed linearly.',
    },
    traits: { stable: false, inPlace: false, recursive: false },
    source: patienceSource,
    examples: { default: [4, 2, 7, 3, 8, 1, 6, 5], bestCase: reversed, worstCase: ordered },
    tags: ['piles', 'binary search', 'heap merge', 'subsequences'],
  },
  {
    id: 'tree',
    name: 'Tree Sort',
    family: 'Tree',
    level: 'Advanced',
    summary: 'Inserts values into an unbalanced binary search tree and writes them back by in-order traversal.',
    explanation: [
      'Insert each distinct value into a binary search tree.',
      'Count duplicates at their matching node.',
      'Traverse left, node, and right order to emit sorted values.',
    ],
    limitation: 'Without balancing, ordered unique input degenerates the tree and construction to O(n²).',
    complexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n²)', memory: 'O(n)' },
    traits: { stable: false, inPlace: false, recursive: false },
    source: treeSource,
    examples: { default: [5, 3, 7, 2, 4, 6, 8, 3], bestCase: [4, 2, 6, 1, 3, 5, 7], worstCase: ordered },
    tags: ['binary search tree', 'in-order traversal', 'duplicate counts', 'unbalanced'],
  },
  {
    id: 'strand',
    name: 'Strand Sort',
    family: 'Selection',
    level: 'Advanced',
    summary: 'Extracts increasing strands from the remaining values and stably merges each into the result.',
    explanation: [
      'Start a strand with the first remaining value.',
      'Extract every later value that can extend the nondecreasing strand.',
      'Stably merge the strand into the accumulated sorted result.',
    ],
    limitation:
      'Repeated front removal from Python lists makes even favorable inputs quadratic in this implementation.',
    complexity: {
      best: 'O(n²)',
      average: 'O(n²)',
      worst: 'O(n²)',
      memory: 'O(n)',
      note: 'Python list pop(0) and repeated list rebuilding dominate the implementation.',
    },
    traits: { stable: true, inPlace: false, recursive: false },
    source: strandSource,
    examples: { default: [1, 4, 7, 2, 5, 8, 3, 6], bestCase: ordered, worstCase: reversed },
    tags: ['strands', 'subsequence extraction', 'stable merge', 'linked-list algorithm'],
  },
  {
    id: 'counting',
    name: 'Counting Sort',
    family: 'Distribution',
    level: 'Intermediate',
    contract: 'sort-integer-array',
    summary: 'Counts offset integer keys and uses cumulative totals to place values in stable order.',
    explanation: [
      'Validate integer keys and find their minimum and maximum.',
      'Count each offset key and convert counts to ending positions.',
      'Traverse backward to place values stably into an output array.',
    ],
    limitation:
      'Dense counting storage depends on the key range; very sparse ranges trigger a slower grouped fallback.',
    complexity: {
      best: 'O(n + k)',
      average: 'O(n + k)',
      worst: 'O(n²)',
      memory: 'O(n + k)',
      note: 'k is the integer range; the guarded sparse-range fallback insertion-sorts distinct keys in quadratic time.',
    },
    traits: { stable: true, inPlace: false, recursive: false },
    source: countingSource,
    examples: {
      default: [4, -2, 3, 4, 1, -2, 0, 3],
      bestCase: [2, 1, 2, 1, 2, 1],
      worstCase: [0, 2000000, -2000000, 1000000, -1000000],
    },
    tags: ['integers', 'non-comparison', 'stable', 'key range'],
  },
  {
    id: 'radix-lsd',
    name: 'LSD Radix Sort',
    family: 'Distribution',
    level: 'Advanced',
    contract: 'sort-integer-array',
    summary: 'Stably sorts integers one decimal digit at a time from least to most significant.',
    explanation: [
      'Offset every integer by the minimum so all working keys are nonnegative.',
      'Stable-count the current base-10 digit into fresh arrays.',
      'Advance to the next digit until the largest offset is exhausted.',
    ],
    limitation: 'It accepts only integers and allocates fresh item and key arrays for every processed digit.',
    complexity: {
      best: 'O(n)',
      average: 'O(d(n + 10))',
      worst: 'O(d(n + 10))',
      memory: 'O(n + 10)',
      note: 'd is the number of decimal digits in the offset key range.',
    },
    traits: { stable: true, inPlace: false, recursive: false },
    source: radixLsdSource,
    examples: {
      default: [170, -45, 75, -90, 802, 24, 2, 66],
      bestCase: [7, 7, 7, 7, 7, 7],
      worstCase: [999999, 1, 100000, 10, 10000, 100],
    },
    tags: ['integers', 'digits', 'base 10', 'stable counting'],
  },
  {
    id: 'bucket',
    name: 'Bucket Sort',
    family: 'Distribution',
    level: 'Intermediate',
    summary: 'Distributes numeric values across range-based buckets, sorts each bucket, and concatenates them.',
    explanation: [
      'Measure the numeric span and create one bucket per value.',
      'Map each value proportionally into a bucket.',
      'Insertion-sort every bucket and concatenate them in range order.',
    ],
    limitation: 'Skewed data can collect in one bucket and reduce performance to quadratic time.',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n²)',
      memory: 'O(n)',
      note: 'Linear average time assumes values are distributed reasonably evenly across buckets.',
    },
    traits: { stable: true, inPlace: false, recursive: false },
    source: bucketSource,
    examples: {
      default: [0.42, -0.18, 0.73, 0.11, 0.95, -0.04, 0.56, 0.31],
      bestCase: [0.1, 0.25, 0.4, 0.55, 0.7, 0.85],
      worstCase: [0, 0.001, 0.002, 0.003, 0.004, 1],
    },
    tags: ['distribution', 'numeric range', 'insertion buckets', 'uniform data'],
  },
];

export const ALGORITHMS: AlgorithmDefinition[] = SORTING_ALGORITHMS.map((algorithm) => ({
  ...algorithm,
  kind: 'sort',
  problem: 'Sorting',
  contract: algorithm.contract ?? 'sort-numeric-array',
}));

export const ALGORITHM_BY_ID = Object.fromEntries(ALGORITHMS.map((algorithm) => [algorithm.id, algorithm])) as Record<
  AlgorithmId,
  AlgorithmDefinition
>;

export const DEFAULT_ALGORITHM_ID: AlgorithmId = 'bubble';
export const DEFAULT_SOURCE = ALGORITHM_BY_ID[DEFAULT_ALGORITHM_ID].source;
