import coinChangeCountSource from '../python/coin_change_count.py?raw';
import coinChangeMinimumSource from '../python/coin_change_minimum.py?raw';
import editDistanceSource from '../python/edit_distance.py?raw';
import fibonacciMemoizationSource from '../python/fibonacci_memoization.py?raw';
import fibonacciTabulationSource from '../python/fibonacci_tabulation.py?raw';
import gridPathsSource from '../python/grid_paths.py?raw';
import longestIncreasingSubsequenceSource from '../python/longest_increasing_subsequence.py?raw';
import matrixChainMultiplicationSource from '../python/matrix_chain_multiplication.py?raw';
import minimumPathSumSource from '../python/minimum_path_sum.py?raw';
import partitionEqualSubsetSumSource from '../python/partition_equal_subset_sum.py?raw';
import rodCuttingSource from '../python/rod_cutting.py?raw';
import unboundedKnapsackSource from '../python/unbounded_knapsack.py?raw';
import zeroOneKnapsackSource from '../python/zero_one_knapsack.py?raw';
import type { SolveAlgorithmDefinition } from '../types';

export const DP_ALGORITHMS: SolveAlgorithmDefinition[] = [
  {
    kind: 'solve',
    id: 'fibonacci-memoization',
    problem: 'Dynamic Programming',
    contract: 'nonnegative-index',
    name: 'Fibonacci Memoization',
    family: 'Sequence DP',
    level: 'Beginner',
    summary: 'Computes a Fibonacci number top-down while caching every solved index.',
    explanation: [
      'Seed F(0) and F(1).',
      'Recursively request the two preceding values.',
      'Cache each sum so every index is solved once.',
    ],
    limitation: "The recursive call depth grows with n and can reach Python's recursion limit.",
    complexity: {
      best: 'O(1)',
      average: 'O(n)',
      worst: 'O(n)',
      memory: 'O(n)',
      note: 'The cache and recursion stack both grow linearly.',
    },
    source: fibonacciMemoizationSource,
    demo: { input: { n: 10 }, expected: 55 },
    tags: ['top-down', 'memoization', 'recursion', 'sequence'],
  },
  {
    kind: 'solve',
    id: 'fibonacci-tabulation',
    problem: 'Dynamic Programming',
    contract: 'nonnegative-index',
    name: 'Fibonacci Tabulation',
    family: 'Sequence DP',
    level: 'Beginner',
    summary: 'Computes a Fibonacci number by filling all values from zero through n.',
    explanation: [
      'Handle the two base indices.',
      'Allocate a table through n.',
      'Fill each cell from the previous two cells.',
    ],
    limitation: 'This teaching implementation retains the full table although two values would suffice.',
    complexity: { best: 'O(1)', average: 'O(n)', worst: 'O(n)', memory: 'O(n)' },
    source: fibonacciTabulationSource,
    demo: { input: { n: 10 }, expected: 55 },
    tags: ['bottom-up', 'tabulation', 'sequence', 'iteration'],
  },
  {
    kind: 'solve',
    id: 'zero-one-knapsack',
    problem: 'Dynamic Programming',
    contract: 'weighted-capacity',
    name: '0/1 Knapsack',
    family: 'Capacity DP',
    level: 'Intermediate',
    summary: 'Finds the maximum value obtainable when each weighted item may be selected once.',
    explanation: [
      'Store the best value for every capacity.',
      'Process one item at a time.',
      'Scan capacities backward so the current item cannot be reused.',
    ],
    limitation: 'Runtime is pseudo-polynomial in the numeric capacity rather than its bit length.',
    complexity: {
      best: 'O(nC)',
      average: 'O(nC)',
      worst: 'O(nC)',
      memory: 'O(C)',
      note: 'n is the item count and C is capacity.',
    },
    source: zeroOneKnapsackSource,
    demo: { input: { weights: [1, 3, 4, 5], values: [1, 4, 5, 7], capacity: 7 }, expected: 9 },
    tags: ['0/1', 'capacity', 'optimization', 'one-dimensional table'],
  },
  {
    kind: 'solve',
    id: 'unbounded-knapsack',
    problem: 'Dynamic Programming',
    contract: 'weighted-capacity',
    name: 'Unbounded Knapsack',
    family: 'Capacity DP',
    level: 'Intermediate',
    summary: 'Finds the maximum value obtainable when every positive-weight item may be reused.',
    explanation: [
      'Store the best value for every capacity.',
      'Try every fitting item at each capacity.',
      'Extend a smaller solved capacity with another copy of that item.',
    ],
    limitation: 'Runtime is pseudo-polynomial and zero-weight items are invalid because reuse would be unbounded.',
    complexity: {
      best: 'O(nC)',
      average: 'O(nC)',
      worst: 'O(nC)',
      memory: 'O(C)',
      note: 'n is the item count and C is capacity.',
    },
    source: unboundedKnapsackSource,
    demo: { input: { weights: [2, 3, 4], values: [4, 5, 7], capacity: 7 }, expected: 13 },
    tags: ['unbounded', 'capacity', 'optimization', 'item reuse'],
  },
  {
    kind: 'solve',
    id: 'coin-change-count',
    problem: 'Dynamic Programming',
    contract: 'coin-change',
    name: 'Coin Change Count',
    family: 'Counting DP',
    level: 'Intermediate',
    summary: 'Counts distinct order-independent coin combinations that total an amount.',
    explanation: [
      'Give amount zero one empty combination.',
      'Process each unique denomination once.',
      'Add ways from the amount one coin smaller.',
    ],
    limitation: 'The table is pseudo-polynomial in the requested amount.',
    complexity: {
      best: 'O(mA)',
      average: 'O(mA)',
      worst: 'O(mA)',
      memory: 'O(A)',
      note: 'm is the denomination count and A is the amount.',
    },
    source: coinChangeCountSource,
    demo: { input: { coins: [1, 2, 5], amount: 5 }, expected: 4 },
    tags: ['counting', 'combinations', 'coins', 'unbounded'],
  },
  {
    kind: 'solve',
    id: 'coin-change-minimum',
    problem: 'Dynamic Programming',
    contract: 'coin-change',
    name: 'Coin Change Minimum',
    family: 'Capacity DP',
    level: 'Intermediate',
    summary: 'Finds the fewest coins needed to total an amount, returning -1 when impossible.',
    explanation: [
      'Set amount zero to zero coins.',
      'Build answers in increasing amount order.',
      'Choose the cheapest reachable predecessor across all coins.',
    ],
    limitation: 'The table is pseudo-polynomial in the requested amount.',
    complexity: {
      best: 'O(mA)',
      average: 'O(mA)',
      worst: 'O(mA)',
      memory: 'O(A)',
      note: 'm is the denomination count and A is the amount.',
    },
    source: coinChangeMinimumSource,
    demo: { input: { coins: [1, 2, 5], amount: 11 }, expected: 3 },
    tags: ['minimum', 'coins', 'unbounded', 'optimization'],
  },
  {
    kind: 'solve',
    id: 'longest-increasing-subsequence',
    problem: 'Dynamic Programming',
    contract: 'numeric-sequence',
    name: 'Longest Increasing Subsequence',
    family: 'Subsequence DP',
    level: 'Intermediate',
    summary: 'Returns a deterministic longest strictly increasing subsequence, not only its length.',
    explanation: [
      'Measure the best subsequence ending at every position.',
      'Remember the first predecessor that strictly improves each length.',
      'Backtrack from the first endpoint with maximum length.',
    ],
    limitation: 'The quadratic teaching approach is slower than patience-sorting-based O(n log n) methods.',
    complexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)', memory: 'O(n)' },
    source: longestIncreasingSubsequenceSource,
    demo: { input: { values: [10, 9, 2, 5, 3, 7, 101, 18] }, expected: [2, 5, 7, 101] },
    tags: ['subsequence', 'reconstruction', 'strictly increasing', 'predecessors'],
  },
  {
    kind: 'solve',
    id: 'matrix-chain-multiplication',
    problem: 'Dynamic Programming',
    contract: 'matrix-dimensions',
    name: 'Matrix Chain Multiplication',
    family: 'Interval DP',
    level: 'Advanced',
    summary: 'Finds the least scalar multiplication cost over all parenthesizations of a matrix chain.',
    explanation: [
      'Treat each single matrix as a zero-cost interval.',
      'Grow intervals by chain length.',
      'Try every split and retain the least combined multiplication cost.',
    ],
    limitation: 'It reports the optimal cost but does not reconstruct the parenthesization.',
    complexity: {
      best: 'O(n³)',
      average: 'O(n³)',
      worst: 'O(n³)',
      memory: 'O(n²)',
      note: 'n is the number of matrices.',
    },
    source: matrixChainMultiplicationSource,
    demo: { input: { dimensions: [40, 20, 30, 10, 30] }, expected: 26000 },
    tags: ['intervals', 'parenthesization', 'matrices', 'optimization'],
  },
  {
    kind: 'solve',
    id: 'edit-distance',
    problem: 'Dynamic Programming',
    contract: 'string-pair',
    name: 'Edit Distance',
    family: 'String DP',
    level: 'Intermediate',
    summary: 'Computes Levenshtein distance using insertion, deletion, and substitution costs of one.',
    explanation: [
      'Initialize distances from the empty source.',
      'Build one source-prefix row at a time.',
      'Choose insertion, deletion, or matching/substitution for each character pair.',
    ],
    limitation: 'It returns only the distance and does not reconstruct an edit script.',
    complexity: {
      best: 'O(st)',
      average: 'O(st)',
      worst: 'O(st)',
      memory: 'O(t)',
      note: 's and t are the two string lengths; memory follows the target length.',
    },
    source: editDistanceSource,
    demo: { input: { source: 'kitten', target: 'sitting' }, expected: 3 },
    tags: ['Levenshtein', 'strings', 'prefixes', 'rolling rows'],
  },
  {
    kind: 'solve',
    id: 'grid-paths',
    problem: 'Dynamic Programming',
    contract: 'grid-dimensions',
    name: 'Grid Paths',
    family: 'Grid DP',
    level: 'Beginner',
    summary: 'Counts paths from the top-left to bottom-right of a grid using only right and down moves.',
    explanation: [
      'Assign one path along the first row.',
      'Sweep all remaining cells row by row.',
      'Add paths arriving from above and from the left.',
    ],
    limitation: 'The model has no blocked cells and permits only rightward and downward movement.',
    complexity: {
      best: 'O(rc)',
      average: 'O(rc)',
      worst: 'O(rc)',
      memory: 'O(c)',
      note: 'r is rows and c is columns.',
    },
    source: gridPathsSource,
    demo: { input: { rows: 3, columns: 7 }, expected: 28 },
    tags: ['grid', 'counting', 'right and down', 'rolling row'],
  },
  {
    kind: 'solve',
    id: 'minimum-path-sum',
    problem: 'Dynamic Programming',
    contract: 'numeric-grid',
    name: 'Minimum Path Sum',
    family: 'Grid DP',
    level: 'Intermediate',
    summary: 'Finds the minimum top-left to bottom-right sum in a rectangular numeric grid.',
    explanation: [
      'Accumulate the forced first row and column paths.',
      'Sweep the remaining cells in row order.',
      'Add each value to the cheaper arrival from above or left.',
    ],
    limitation: 'Only right and down movement is considered; the grid must be rectangular.',
    complexity: {
      best: 'O(rc)',
      average: 'O(rc)',
      worst: 'O(rc)',
      memory: 'O(c)',
      note: 'r is rows and c is columns.',
    },
    source: minimumPathSumSource,
    demo: {
      input: {
        grid: [
          [1, 3, 1],
          [1, 5, 1],
          [4, 2, 1],
        ],
      },
      expected: 7,
    },
    tags: ['grid', 'minimum', 'right and down', 'rolling row'],
  },
  {
    kind: 'solve',
    id: 'rod-cutting',
    problem: 'Dynamic Programming',
    contract: 'rod-prices',
    name: 'Rod Cutting',
    family: 'Capacity DP',
    level: 'Intermediate',
    summary: 'Maximizes revenue from exactly cutting a rod using prices indexed by piece length.',
    explanation: [
      'Set zero length to zero revenue.',
      'Build the best revenue for every requested prefix length.',
      'Try each priced first cut and append its solved remainder.',
    ],
    limitation: 'Runtime is pseudo-polynomial in rod length and the result does not list the selected cuts.',
    complexity: {
      best: 'O(LP)',
      average: 'O(LP)',
      worst: 'O(LP)',
      memory: 'O(L)',
      note: 'L is rod length and P is the number of listed piece prices; only fitting pieces are visited.',
    },
    source: rodCuttingSource,
    demo: { input: { prices: [1, 5, 8, 9, 10, 17, 17, 20], length: 8 }, expected: 22 },
    tags: ['cuts', 'revenue', 'unbounded', 'optimization'],
  },
  {
    kind: 'solve',
    id: 'partition-equal-subset-sum',
    problem: 'Dynamic Programming',
    contract: 'nonnegative-integer-set',
    name: 'Partition Equal Subset Sum',
    family: 'Subset DP',
    level: 'Intermediate',
    summary: 'Decides whether nonnegative integers can be divided into two subsets with equal sums.',
    explanation: [
      'Reject an odd total immediately.',
      'Target half of the total with a reachability table.',
      'Scan subtotals backward so each value is used at most once.',
    ],
    limitation: 'Runtime and memory are pseudo-polynomial in half the input sum.',
    complexity: {
      best: 'O(n)',
      average: 'O(nS)',
      worst: 'O(nS)',
      memory: 'O(S)',
      note: 'S is half the total; an odd total exits after summation.',
    },
    source: partitionEqualSubsetSumSource,
    demo: { input: { values: [1, 5, 11, 5] }, expected: true },
    tags: ['subset sum', 'partition', 'decision', '0/1'],
  },
];
