import binarySearchSource from '../python/binary_search.py?raw';
import exponentialSearchSource from '../python/exponential_search.py?raw';
import fibonacciSearchSource from '../python/fibonacci_search.py?raw';
import interpolationSearchSource from '../python/interpolation_search.py?raw';
import jumpSearchSource from '../python/jump_search.py?raw';
import linearSearchSource from '../python/linear_search.py?raw';
import lowerBoundSource from '../python/lower_bound.py?raw';
import quickselectSource from '../python/quickselect.py?raw';
import sentinelSearchSource from '../python/sentinel_search.py?raw';
import upperBoundSource from '../python/upper_bound.py?raw';
import type { SolveAlgorithmDefinition } from '../types';

export const SEARCHING_ALGORITHMS: SolveAlgorithmDefinition[] = [
  {
    kind: 'solve',
    id: 'search-linear-first',
    problem: 'Searching',
    contract: 'find-in-array',
    name: 'Linear Search',
    family: 'Sequential Search',
    level: 'Beginner',
    summary: 'Scans from left to right and returns the first index equal to the target.',
    explanation: [
      'Begin at index zero.',
      'Compare each value with the target in order.',
      'Return the first match, or -1 after the scan ends.',
    ],
    limitation: 'It performs a linear number of comparisons when the target is late or absent.',
    complexity: { best: 'O(1)', average: 'O(n)', worst: 'O(n)', memory: 'O(1)' },
    source: linearSearchSource,
    demo: { input: { values: [7, 2, 9, 2, 5], target: 2 }, expected: 1 },
    tags: ['sequential', 'unsorted', 'first occurrence', 'scan'],
  },
  {
    kind: 'solve',
    id: 'search-sentinel-first',
    problem: 'Searching',
    contract: 'find-in-array',
    name: 'Sentinel Search',
    family: 'Sequential Search',
    level: 'Beginner',
    summary: 'Appends the target temporarily so the scan needs no end-of-array check.',
    explanation: [
      'Append the target as a sentinel.',
      'Scan until a matching value is guaranteed to appear.',
      'Remove the sentinel and distinguish a real first match from absence.',
    ],
    limitation: 'The input must be a mutable list, although its original contents are restored before return.',
    complexity: { best: 'O(1)', average: 'O(n)', worst: 'O(n)', memory: 'O(1)' },
    source: sentinelSearchSource,
    demo: { input: { values: [4, 8, 1, 8, 3], target: 8 }, expected: 1 },
    tags: ['sequential', 'sentinel', 'unsorted', 'first occurrence'],
  },
  {
    kind: 'solve',
    id: 'search-binary-first',
    problem: 'Searching',
    contract: 'find-in-array',
    name: 'Binary Search',
    family: 'Binary Search',
    level: 'Beginner',
    summary: 'Halves a sorted search range while retaining the leftmost matching index.',
    explanation: [
      'Compare the target with the middle sorted value.',
      'Discard the half that cannot contain an earlier match.',
      'Continue left after equality and return the first matching index, or -1.',
    ],
    limitation: 'Values must already be sorted in nondecreasing order.',
    complexity: {
      best: 'O(log n)',
      average: 'O(log n)',
      worst: 'O(log n)',
      memory: 'O(1)',
      note: 'Finding the first duplicate continues toward the left boundary after a match.',
    },
    source: binarySearchSource,
    demo: { input: { values: [1, 3, 3, 3, 8, 12], target: 3 }, expected: 1 },
    tags: ['sorted', 'divide and conquer', 'first occurrence', 'logarithmic'],
  },
  {
    kind: 'solve',
    id: 'search-lower-bound',
    problem: 'Searching',
    contract: 'bound-in-sorted-array',
    name: 'Lower Bound',
    family: 'Binary Search',
    level: 'Intermediate',
    summary: 'Finds the insertion index before all existing values equal to the target.',
    explanation: [
      'Maintain a half-open candidate range.',
      'Move right past middle values smaller than the target.',
      'Return the first index whose value is at least the target.',
    ],
    limitation: 'The insertion position is meaningful only when values are sorted in nondecreasing order.',
    complexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(log n)', memory: 'O(1)' },
    source: lowerBoundSource,
    demo: { input: { values: [1, 3, 3, 3, 8, 12], target: 3 }, expected: 1 },
    tags: ['sorted', 'insertion point', 'left boundary', 'binary search'],
  },
  {
    kind: 'solve',
    id: 'search-upper-bound',
    problem: 'Searching',
    contract: 'bound-in-sorted-array',
    name: 'Upper Bound',
    family: 'Binary Search',
    level: 'Intermediate',
    summary: 'Finds the insertion index after all existing values equal to the target.',
    explanation: [
      'Maintain a half-open candidate range.',
      'Move right past middle values less than or equal to the target.',
      'Return the first index whose value is greater than the target.',
    ],
    limitation: 'The insertion position is meaningful only when values are sorted in nondecreasing order.',
    complexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(log n)', memory: 'O(1)' },
    source: upperBoundSource,
    demo: { input: { values: [1, 3, 3, 3, 8, 12], target: 3 }, expected: 4 },
    tags: ['sorted', 'insertion point', 'right boundary', 'binary search'],
  },
  {
    kind: 'solve',
    id: 'search-jump-first',
    problem: 'Searching',
    contract: 'find-in-array',
    name: 'Jump Search',
    family: 'Block Search',
    level: 'Intermediate',
    summary: 'Jumps across square-root-sized sorted blocks, then scans the candidate block.',
    explanation: [
      'Choose a jump length near the square root of the array size.',
      'Skip blocks whose final value is smaller than the target.',
      'Scan the candidate block from its start to return the first match, or -1.',
    ],
    limitation: 'Values must be sorted, and its O(sqrt(n)) comparisons are slower than binary search in memory.',
    complexity: { best: 'O(1)', average: 'O(√n)', worst: 'O(√n)', memory: 'O(1)' },
    source: jumpSearchSource,
    demo: { input: { values: [1, 2, 4, 4, 4, 9, 15, 21], target: 4 }, expected: 2 },
    tags: ['sorted', 'blocks', 'square root', 'first occurrence'],
  },
  {
    kind: 'solve',
    id: 'search-exponential-first',
    problem: 'Searching',
    contract: 'find-in-array',
    name: 'Exponential Search',
    family: 'Range Expansion',
    level: 'Intermediate',
    summary: 'Doubles a sorted prefix bound before binary-searching the bracketed range.',
    explanation: [
      'Check the first value, then double an index while values remain below the target.',
      'Use the previous and current powers of two as a search bracket.',
      'Binary-search leftward within the bracket for the first match, or return -1.',
    ],
    limitation: 'Values must be sorted; random-access binary search is usually simpler when the full size is known.',
    complexity: {
      best: 'O(1)',
      average: 'O(log i)',
      worst: 'O(log n)',
      memory: 'O(1)',
      note: "i is the first matching index, or the target's insertion region when absent.",
    },
    source: exponentialSearchSource,
    demo: { input: { values: [2, 5, 5, 5, 11, 19, 31, 48], target: 5 }, expected: 1 },
    tags: ['sorted', 'doubling', 'binary search', 'unbounded arrays'],
  },
  {
    kind: 'solve',
    id: 'search-interpolation-first',
    problem: 'Searching',
    contract: 'find-in-array',
    name: 'Interpolation Search',
    family: 'Value Probing',
    level: 'Advanced',
    summary: 'Estimates the target position from endpoint values in a sorted numeric range.',
    explanation: [
      'Map the target proportionally between the low and high endpoint values.',
      'Discard the side excluded by the probed value.',
      'Continue left after equality to return the first match, or -1.',
    ],
    limitation: 'It requires sorted numeric values and degrades to linear time on badly skewed distributions.',
    complexity: {
      best: 'O(1)',
      average: 'O(log log n)',
      worst: 'O(n)',
      memory: 'O(1)',
      note: 'The average bound assumes approximately uniform numeric values.',
    },
    source: interpolationSearchSource,
    demo: { input: { values: [10, 20, 30, 30, 30, 40, 50], target: 30 }, expected: 2 },
    tags: ['sorted', 'numeric', 'interpolation', 'uniform distribution'],
  },
  {
    kind: 'solve',
    id: 'search-fibonacci-first',
    problem: 'Searching',
    contract: 'find-in-array',
    name: 'Fibonacci Search',
    family: 'Interval Reduction',
    level: 'Advanced',
    summary: 'Narrows a sorted range using Fibonacci-sized offsets and returns its first match.',
    explanation: [
      'Build the smallest Fibonacci interval covering the array.',
      'Probe at the lower Fibonacci offset and shrink the interval by one or two steps.',
      'Keep reducing toward the left after equality and return the earliest match, or -1.',
    ],
    limitation: 'Values must be sorted, and the bookkeeping is more complex than ordinary binary search.',
    complexity: {
      best: 'O(log n)',
      average: 'O(log n)',
      worst: 'O(log n)',
      memory: 'O(1)',
      note: 'This first-occurrence variant continues reducing the interval after equality.',
    },
    source: fibonacciSearchSource,
    demo: { input: { values: [1, 4, 4, 4, 7, 12, 18, 25], target: 4 }, expected: 1 },
    tags: ['sorted', 'Fibonacci numbers', 'first occurrence', 'interval reduction'],
  },
  {
    kind: 'solve',
    id: 'search-quickselect-kth',
    problem: 'Searching',
    contract: 'select-kth',
    name: 'Quickselect',
    family: 'Selection',
    level: 'Advanced',
    summary: 'Partitions a copied array until the zero-based kth-smallest value reaches its final rank.',
    explanation: [
      'Validate zero-based k and copy the input values.',
      'Partition the active range around its final value.',
      'Continue only in the side containing rank k, then return that value.',
    ],
    limitation: 'A deterministic last-value pivot can cause quadratic time on adversarial inputs.',
    complexity: {
      best: 'O(n)',
      average: 'O(n)',
      worst: 'O(n²)',
      memory: 'O(n)',
      note: "Linear auxiliary memory preserves the caller's input; k is zero-based.",
    },
    source: quickselectSource,
    demo: { input: { values: [9, 1, 7, 3, 7, 2], k: 3 }, expected: 7 },
    tags: ['selection', 'kth smallest', 'partition', 'zero-based rank'],
  },
];
