import ahoCorasickSource from '../python/aho_corasick.py?raw';
import boyerMooreSource from '../python/boyer_moore.py?raw';
import horspoolSource from '../python/horspool.py?raw';
import kmpSource from '../python/kmp.py?raw';
import lcpSource from '../python/longest_common_prefix.py?raw';
import lcsSource from '../python/longest_common_subsequence.py?raw';
import levenshteinSource from '../python/levenshtein_distance.py?raw';
import manacherSource from '../python/manacher.py?raw';
import naiveSearchSource from '../python/naive_search.py?raw';
import rabinKarpSource from '../python/rabin_karp.py?raw';
import trieLookupSource from '../python/trie_lookup.py?raw';
import zAlgorithmSource from '../python/z_algorithm.py?raw';
import type { SolveAlgorithmDefinition } from '../types';

export const STRING_ALGORITHMS: SolveAlgorithmDefinition[] = [
  {
    kind: 'solve',
    id: 'naive-search',
    problem: 'String',
    contract: 'substring-first-index',
    name: 'Naive Search',
    family: 'Exact Matching',
    level: 'Beginner',
    summary: 'Checks the pattern from every possible starting position and returns its first match.',
    explanation: [
      'Try each viable text position from left to right.',
      'Compare pattern characters until a mismatch occurs.',
      'Return the first complete match, with an empty pattern defined at index zero.',
    ],
    limitation: 'Repeated prefixes can force a fresh pattern scan at every text position.',
    complexity: {
      best: 'O(m)',
      average: 'O(nm)',
      worst: 'O(nm)',
      memory: 'O(1)',
      note: 'n is text length and m is pattern length.',
    },
    source: naiveSearchSource,
    demo: { input: { text: 'abracadabra', pattern: 'cada' }, expected: 4 },
    tags: ['substring', 'brute force', 'first match'],
  },
  {
    kind: 'solve',
    id: 'kmp',
    problem: 'String',
    contract: 'substring-first-index',
    name: 'Knuth-Morris-Pratt',
    family: 'Exact Matching',
    level: 'Intermediate',
    summary: 'Reuses matched pattern borders to avoid revisiting text characters after a mismatch.',
    explanation: [
      "Build the pattern's longest-prefix-suffix table.",
      'Advance through the text while falling back through known borders.',
      'Return when the complete pattern first matches, or minus one if it never does.',
    ],
    limitation: 'Prefix preprocessing adds machinery that offers little benefit for tiny patterns.',
    complexity: {
      best: 'O(n + m)',
      average: 'O(n + m)',
      worst: 'O(n + m)',
      memory: 'O(m)',
      note: 'n is text length and m is pattern length.',
    },
    source: kmpSource,
    demo: { input: { text: 'ababcabcabababd', pattern: 'ababd' }, expected: 10 },
    tags: ['substring', 'prefix table', 'linear'],
  },
  {
    kind: 'solve',
    id: 'z-algorithm',
    problem: 'String',
    contract: 'substring-first-index',
    name: 'Z Algorithm',
    family: 'Exact Matching',
    level: 'Intermediate',
    summary: 'Finds pattern occurrences by measuring prefix matches in a combined pattern and text sequence.',
    explanation: [
      'Join the pattern and text with a collision-proof sentinel.',
      'Maintain a window whose contents match the combined prefix.',
      'The first text position with a Z value at least the pattern length is the answer.',
    ],
    limitation: 'The combined sequence and Z table require linear auxiliary memory.',
    complexity: { best: 'O(n + m)', average: 'O(n + m)', worst: 'O(n + m)', memory: 'O(n + m)' },
    source: zAlgorithmSource,
    demo: { input: { text: 'mississippi', pattern: 'issi' }, expected: 1 },
    tags: ['substring', 'Z values', 'linear'],
  },
  {
    kind: 'solve',
    id: 'rabin-karp',
    problem: 'String',
    contract: 'substring-first-index',
    name: 'Rabin-Karp',
    family: 'Exact Matching',
    level: 'Intermediate',
    summary: 'Slides a rolling hash over the text and verifies windows whose hash equals the pattern hash.',
    explanation: [
      'Hash the pattern and first equal-length text window.',
      'Roll the window hash forward in constant time.',
      'Verify equal hashes against the actual strings so collisions cannot produce a false match.',
    ],
    limitation: 'Hash collisions can trigger extra full-window comparisons and quadratic worst-case time.',
    complexity: { best: 'O(n + m)', average: 'O(n + m)', worst: 'O(nm)', memory: 'O(1)' },
    source: rabinKarpSource,
    demo: { input: { text: 'the quick brown fox', pattern: 'brown' }, expected: 10 },
    tags: ['substring', 'rolling hash', 'verified match'],
  },
  {
    kind: 'solve',
    id: 'boyer-moore',
    problem: 'String',
    contract: 'substring-first-index',
    name: 'Boyer-Moore',
    family: 'Exact Matching',
    level: 'Advanced',
    summary: 'Compares right to left and shifts by both bad-character and good-suffix information.',
    explanation: [
      "Precompute each character's last position and good-suffix shifts.",
      'Compare an aligned pattern from its right edge.',
      'Move by the larger safe mismatch shift until the first match is found.',
    ],
    limitation: 'Its preprocessing and worst-case behavior are less attractive for short patterns.',
    complexity: {
      best: 'O(n / m)',
      average: 'O(n)',
      worst: 'O(nm)',
      memory: 'O(m + k)',
      note: 'k is the number of distinct pattern characters; this implementation uses the two classic shift rules.',
    },
    source: boyerMooreSource,
    demo: { input: { text: 'HERE IS A SIMPLE EXAMPLE', pattern: 'EXAMPLE' }, expected: 17 },
    tags: ['substring', 'bad character', 'good suffix'],
  },
  {
    kind: 'solve',
    id: 'horspool',
    problem: 'String',
    contract: 'substring-first-index',
    name: 'Horspool',
    family: 'Exact Matching',
    level: 'Intermediate',
    summary: "Simplifies Boyer-Moore by shifting from the text character aligned with the pattern's end.",
    explanation: [
      'Build shifts from every pattern character except the last.',
      'Compare each alignment from right to left.',
      "On mismatch, shift using the character under the pattern's final position.",
    ],
    limitation: 'Highly repetitive data can still require quadratic character comparisons.',
    complexity: {
      best: 'O(n / m)',
      average: 'O(n)',
      worst: 'O(nm)',
      memory: 'O(k)',
      note: 'k is the number of distinct pattern characters.',
    },
    source: horspoolSource,
    demo: { input: { text: 'trusthardtoothbrushes', pattern: 'tooth' }, expected: 9 },
    tags: ['substring', 'shift table', 'right to left'],
  },
  {
    kind: 'solve',
    id: 'aho-corasick',
    problem: 'String',
    contract: 'multi-pattern-all-matches',
    name: 'Aho-Corasick',
    family: 'Multiple Pattern Matching',
    level: 'Advanced',
    summary: 'Scans once through the text with a trie augmented by suffix-failure links.',
    explanation: [
      'Insert every nonempty pattern into a trie.',
      'Build failure links and inherit suffix outputs breadth first.',
      'Return all matches ordered by start index then original pattern position; duplicates are preserved and empty patterns match index zero.',
    ],
    limitation: 'The automaton can consume substantial memory when patterns share few prefixes.',
    complexity: {
      best: 'O(P + n)',
      average: 'O(P + n + z log z)',
      worst: 'O(P + n + z log z)',
      memory: 'O(P + z)',
      note: 'P is total pattern length and z is the number of matches; sorting z matches enforces the output contract.',
    },
    source: ahoCorasickSource,
    demo: {
      input: { text: 'ushers', patterns: ['he', 'she', 'hers', 'his'] },
      expected: [
        { index: 1, pattern: 'she' },
        { index: 2, pattern: 'he' },
        { index: 2, pattern: 'hers' },
      ],
    },
    tags: ['multiple patterns', 'trie', 'failure links', 'all matches'],
  },
  {
    kind: 'solve',
    id: 'trie-lookup',
    problem: 'String',
    contract: 'trie-exact-membership',
    name: 'Trie Lookup',
    family: 'Prefix Tree',
    level: 'Beginner',
    summary: 'Builds a character trie and reports whether the complete query was inserted as a word.',
    explanation: [
      'Insert words one character edge at a time.',
      'Mark the node ending each complete word.',
      'Follow the query path and return true only if its final node is terminal.',
    ],
    limitation: 'Dictionary-based child maps add memory overhead per trie node.',
    complexity: {
      best: 'O(P + q)',
      average: 'O(P + q)',
      worst: 'O(P + q)',
      memory: 'O(P)',
      note: 'P is total word length and q is query length.',
    },
    source: trieLookupSource,
    demo: { input: { words: ['cat', 'car', 'dog'], query: 'car' }, expected: true },
    tags: ['trie', 'membership', 'exact word'],
  },
  {
    kind: 'solve',
    id: 'longest-common-prefix',
    problem: 'String',
    contract: 'longest-common-prefix',
    name: 'Longest Common Prefix',
    family: 'Prefix Comparison',
    level: 'Beginner',
    summary: 'Shrinks a candidate prefix until it is shared by every input string.',
    explanation: [
      'Use the first string as the initial prefix bound.',
      'Compare each following string only within that bound.',
      'Return the surviving prefix, or an empty string for an empty collection.',
    ],
    limitation: 'It only captures a shared prefix, not common text appearing later in the strings.',
    complexity: {
      best: 'O(s)',
      average: 'O(S)',
      worst: 'O(S)',
      memory: 'O(1)',
      note: 'S is the number of inspected characters and s is the number of strings.',
    },
    source: lcpSource,
    demo: { input: { strings: ['flower', 'flow', 'flight'] }, expected: 'fl' },
    tags: ['prefix', 'strings', 'horizontal scan'],
  },
  {
    kind: 'solve',
    id: 'manacher',
    problem: 'String',
    contract: 'longest-palindromic-substring',
    name: "Manacher's Algorithm",
    family: 'Palindrome',
    level: 'Advanced',
    summary: 'Reuses mirrored palindrome radii to find the longest palindromic substring in linear time.',
    explanation: [
      'Compute odd palindrome radii inside the current rightmost boundary.',
      'Repeat for even palindromes with the corresponding mirror rule.',
      'Choose the longest substring and the earliest start when lengths tie.',
    ],
    limitation: 'Separate odd and even radius passes make the implementation less intuitive than center expansion.',
    complexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)', memory: 'O(n)' },
    source: manacherSource,
    demo: { input: { text: 'babad' }, expected: 'bab' },
    tags: ['palindrome', 'linear', 'earliest tie'],
  },
  {
    kind: 'solve',
    id: 'levenshtein-distance',
    problem: 'String',
    contract: 'levenshtein-distance',
    name: 'Levenshtein Distance',
    family: 'Edit Distance',
    level: 'Intermediate',
    summary: 'Computes the minimum single-character insertions, deletions, and substitutions between two strings.',
    explanation: [
      'Initialize edit costs for transforming an empty prefix.',
      'Fill each next row from insertion, deletion, and substitution choices.',
      'Keep only two rows and return the final minimum cost.',
    ],
    limitation: 'Quadratic time is expensive for very long strings even with reduced memory.',
    complexity: {
      best: 'O(ab)',
      average: 'O(ab)',
      worst: 'O(ab)',
      memory: 'O(min(a, b))',
      note: 'a and b are the two string lengths.',
    },
    source: levenshteinSource,
    demo: { input: { first: 'kitten', second: 'sitting' }, expected: 3 },
    tags: ['dynamic programming', 'edit distance', 'two rows'],
  },
  {
    kind: 'solve',
    id: 'longest-common-subsequence',
    problem: 'String',
    contract: 'longest-common-subsequence',
    name: 'Longest Common Subsequence',
    family: 'Sequence Alignment',
    level: 'Intermediate',
    summary: 'Builds suffix optimum lengths and reconstructs one deterministic longest shared subsequence.',
    explanation: [
      'Fill a suffix table from the ends of both strings.',
      'Take equal characters while reconstructing from the table.',
      'When unequal choices tie, advance in the first string for a deterministic result.',
    ],
    limitation: 'Reconstructing the subsequence requires a quadratic table rather than two rolling rows.',
    complexity: {
      best: 'O(ab)',
      average: 'O(ab)',
      worst: 'O(ab)',
      memory: 'O(ab)',
      note: 'a and b are the two string lengths.',
    },
    source: lcsSource,
    demo: { input: { first: 'ABCBDAB', second: 'BDCABA' }, expected: 'BDAB' },
    tags: ['dynamic programming', 'subsequence', 'deterministic tie'],
  },
];
